/// Autogenerated by Thrift Compiler (0.20.0)
/// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
///  @generated


// ignore_for_file: unused_import
library general.src.annotation;

//import 'package:thrift/src/protocol/t_protocol.dart';
import 'package:thrift/thrift.dart';
import 'dart:typed_data';
import 'class_object.dart';
import 'object.dart';
import 'amount.dart';
import 'variant.dart';
import 'annotation.dart';
import 'method_argument.dart';
import 'method_description.dart';
import 'byte_code_object.dart';
import 'method_signature.dart';
import 'method_short_argument.dart';
import 'method_short_description.dart';
import 'api_response.dart';

class Annotation implements TBase {
  static final TStruct _STRUCT_DESC = TStruct("Annotation");
  static final TField _NAME_FIELD_DESC = TField("name", TType.STRING, 1);
  static final TField _ARGUMENTS_FIELD_DESC = TField("arguments", TType.MAP, 2);

  String _name = "";
  static const int NAME = 1;
  Map<String, String> _arguments = Map<String, String>();
  static const int ARGUMENTS = 2;


  Annotation() {
  }

  // name
  String get name => this._name;

  set name(String name) {
    this._name = name;
  }

  // arguments
  Map<String, String> get arguments => this._arguments;

  set arguments(Map<String, String> arguments) {
    this._arguments = arguments;
  }

  @override
  read(TProtocol iprot) {
    bool __isset_name = false;
    bool __isset_arguments = false;
    TField field;
    iprot.readStructBegin();
    while (true) {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) {
        break;
      }
      switch (field.id) {
        case NAME:
          if (field.type == TType.STRING) {
            this.name = iprot.readString();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case ARGUMENTS:
          if (field.type == TType.MAP) {
            {
              TMap _map22 = iprot.readMapBegin();
              this.arguments = Map<String, String>();
              for (int _i23 = 0; _i23 < _map22.length; ++_i23) {
                String _key24;
                String _val25;
                _key24 = iprot.readString();
                _val25 = iprot.readString();
                this.arguments[_key24] = _val25;
              }
              iprot.readMapEnd();
            }
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  @override
  write(TProtocol oprot) {
    validate();

    oprot.writeStructBegin(_STRUCT_DESC);
    oprot.writeFieldBegin(_NAME_FIELD_DESC);
    oprot.writeString(this.name);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_ARGUMENTS_FIELD_DESC);
    {
      oprot.writeMapBegin(TMap(TType.STRING, TType.STRING, this.arguments.length));
      for (var elem27 in this.arguments.keys) {
        oprot.writeString(elem27);
        oprot.writeString(this.arguments[elem27]!);
      }
      oprot.writeMapEnd();
    }
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @override
  String toString() {
    StringBuffer ret = StringBuffer("Annotation(");

    ret.write("name:");
    ret.write(this.name);

    ret.write(", ");
    ret.write("arguments:");
    ret.write(this.arguments);

    ret.write(")");

    return ret.toString();
  }

  validate() {
    // check for required fields
    // check that fields of type enum have valid values
  }

}

