/// Autogenerated by Thrift Compiler (0.20.0)
/// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
///  @generated


// ignore_for_file: unused_import
library general.src.method_short_description;

//import 'package:thrift/src/protocol/t_protocol.dart';
import 'package:thrift/thrift.dart';
import 'class_object.dart';
import 'object.dart';
import 'amount.dart';
import 'variant.dart';
import 'annotation.dart';
import 'method_argument.dart';
import 'method_description.dart';
import 'byte_code_object.dart';
import 'method_signature.dart';
import 'method_short_argument.dart';
import 'method_short_description.dart';
import 'api_response.dart';

class MethodShortDescription implements TBase {
  static final TStruct _STRUCT_DESC = TStruct("MethodShortDescription");
  static final TField _NAME_FIELD_DESC = TField("name", TType.STRING, 1);
  static final TField _RET_VALUES_FIELD_DESC = TField("retValues", TType.LIST, 2);
  static final TField _ARGUMENTS_FIELD_DESC = TField("arguments", TType.LIST, 3);
  static final TField _MODIFIERS_FIELD_DESC = TField("modifiers", TType.LIST, 4);
  static final TField _ADDRESS_FIELD_DESC = TField("address", TType.STRING, 5);

  String _name = "";
  static const int NAME = 1;
  List<MethodShortArgument> _retValues = [];
  static const int RETVALUES = 2;
  List<MethodShortArgument> _arguments = [];
  static const int ARGUMENTS = 3;
  List<String>? _modifiers;
  static const int MODIFIERS = 4;
  String? _address;
  static const int ADDRESS = 5;

  //bool __isset_modifiers = false;
  //bool __isset_address = false;

  MethodShortDescription() {
  }

  // name
  String get name => this._name;

  set name(String name) {
    this._name = name;
  }

  // retValues
  List<MethodShortArgument> get retValues => this._retValues;

  set retValues(List<MethodShortArgument> retValues) {
    this._retValues = retValues;
  }

  // arguments
  List<MethodShortArgument> get arguments => this._arguments;

  set arguments(List<MethodShortArgument> arguments) {
    this._arguments = arguments;
  }

  // modifiers
  List<String>? get modifiers => this._modifiers;

  set modifiers(List<String>? modifiers) {
    this._modifiers = modifiers;
  }

  bool isSetModifiers() => this.modifiers != null;

  unsetModifiers() {
    this.modifiers = null;
  }

  // address
  String? get address => this._address;

  set address(String? address) {
    this._address = address;
    //this.__isset_address = true;
  }

  bool isSetAddress() => this.address != null;

  unsetAddress() {
    this.address = null;
  }

  @override
  read(TProtocol iprot) {
    bool __isset_name = false;
    bool __isset_retValues = false;
    bool __isset_arguments = false;
    TField field;
    iprot.readStructBegin();
    while (true) {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) {
        break;
      }
      switch (field.id) {
        case NAME:
          if (field.type == TType.STRING) {
            this.name = iprot.readString();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case RETVALUES:
          if (field.type == TType.LIST) {
            {
              TList _list44 = iprot.readListBegin();
              this.retValues = [];
              for (int _i45 = 0; _i45 < _list44.length; ++_i45) {
                MethodShortArgument _elem46;//declare element for this.retValues
                _elem46 = MethodShortArgument();
                _elem46.read(iprot);
                this.retValues.add(_elem46);//add element to parent this.retValues
              }
              iprot.readListEnd();
            }
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case ARGUMENTS:
          if (field.type == TType.LIST) {
            {
              TList _list47 = iprot.readListBegin();
              this.arguments = [];
              for (int _i48 = 0; _i48 < _list47.length; ++_i48) {
                MethodShortArgument _elem49;//declare element for this.arguments
                _elem49 = MethodShortArgument();
                _elem49.read(iprot);
                this.arguments.add(_elem49);//add element to parent this.arguments
              }
              iprot.readListEnd();
            }
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case MODIFIERS:
          if (field.type == TType.LIST) {
            {
              TList _list50 = iprot.readListBegin();
              this.modifiers = [];
              for (int _i51 = 0; _i51 < _list50.length; ++_i51) {
                String _elem52;//declare element for this.modifiers
                _elem52 = iprot.readString();
                this.modifiers?.add(_elem52);//add element to parent this.modifiers
              }
              iprot.readListEnd();
            }
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case ADDRESS:
          if (field.type == TType.STRING) {
            this.address = iprot.readString();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  @override
  write(TProtocol oprot) {
    validate();

    oprot.writeStructBegin(_STRUCT_DESC);
    oprot.writeFieldBegin(_NAME_FIELD_DESC);
    oprot.writeString(this.name);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_RET_VALUES_FIELD_DESC);
    {
      oprot.writeListBegin(TList(TType.STRUCT, this.retValues.length));
      for (var elem53 in this.retValues) {
        elem53.write(oprot);
      }
      oprot.writeListEnd();
    }
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_ARGUMENTS_FIELD_DESC);
    {
      oprot.writeListBegin(TList(TType.STRUCT, this.arguments.length));
      for (var elem54 in this.arguments) {
        elem54.write(oprot);
      }
      oprot.writeListEnd();
    }
    oprot.writeFieldEnd();
    if (isSetModifiers()) {
      oprot.writeFieldBegin(_MODIFIERS_FIELD_DESC);
      {
        oprot.writeListBegin(TList(TType.STRING, this.modifiers!.length));
        for (var elem55 in this.modifiers!) {
          oprot.writeString(elem55);
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    if (isSetAddress()) {
      oprot.writeFieldBegin(_ADDRESS_FIELD_DESC);
      oprot.writeString(this.address!);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @override
  String toString() {
    StringBuffer ret = StringBuffer("MethodShortDescription(");

    ret.write("name:");
    ret.write(this.name);

    ret.write(", ");
    ret.write("retValues:");
    ret.write(this.retValues);

    ret.write(", ");
    ret.write("arguments:");
    ret.write(this.arguments);

    if (isSetModifiers()) {
      ret.write(", ");
      ret.write("modifiers:");
      if (this.modifiers == null) {
        ret.write("null");
      } else {
        ret.write(this.modifiers);
      }
    }

    if (isSetAddress()) {
      ret.write(", ");
      ret.write("address:");
      if (this.address == null) {
        ret.write("null");
      } else {
        ret.write(this.address);
      }
    }

    ret.write(")");

    return ret.toString();
  }

  validate() {
    // check for required fields
    // check that fields of type enum have valid values
  }

}

