/// Autogenerated by Thrift Compiler (0.20.0)
/// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
///  @generated


// ignore_for_file: unused_import
library api.src.cumulative_amount;

//import 'package:thrift/src/protocol/t_protocol.dart';
import 'package:thrift/thrift.dart';
import 'dart:typed_data';
import 'transaction_type.dart';
import 'smart_operation_state.dart';
import 'transaction_state.dart';
import 'tokens_list_sort_field.dart';
import 'token_holders_sort_field.dart';
import 'wallets_list_sort.dart';
import 'package:thrifttest/general/lib/general.dart' as t_general;
import 'amount_commission.dart';
import 'cumulative_amount.dart';
import 'smart_contract_deploy.dart';
import 'smart_contract.dart';
import 'smart_contract_invocation.dart';
import 'transaction_id.dart';
import 'token_deploy_trans_info.dart';
import 'token_transfer_trans_info.dart';
import 'smart_deploy_trans_info.dart';
import 'smart_execution_trans_info.dart';
import 'extra_fee.dart';
import 'smart_state_trans_info.dart';
import 'smart_trans_info.dart';
import 'transaction.dart';
import 'sealed_transaction.dart';
import 'short_transaction.dart';
import 'pool.dart';
import 'delegated_item.dart';
import 'delegated.dart';
import 'wallet_data.dart';
import 'period_stats.dart';
import 'wallet_data_get_result.dart';
import 'wallet_id_get_result.dart';
import 'wallet_transactions_count_get_result.dart';
import 'wallet_balance_get_result.dart';
import 'transaction_get_result.dart';
import 'transactions_get_result.dart';
import 'transaction_flow_result.dart';
import 'single_token_query.dart';
import 'single_query.dart';
import 'transactions_query.dart';
import 'selected_token_transfers.dart';
import 'public_key_transactions.dart';
import 'filtered_transactions_list_result.dart';
import 'pool_list_get_result.dart';
import 'pool_info_get_result.dart';
import 'pool_transactions_get_result.dart';
import 'stats_get_result.dart';
import 'smart_contract_get_result.dart';
import 'smart_contract_addresses_list_get_result.dart';
import 'smart_contracts_list_get_result.dart';
import 'transactions_state_get_result.dart';
import 'smart_method_params_get_result.dart';
import 'contract_all_methods_get_result.dart';
import 'smart_contract_method_argument.dart';
import 'smart_contract_method.dart';
import 'smart_contract_data_result.dart';
import 'smart_contract_compile_result.dart';
import 'token_info.dart';
import 'token_transaction.dart';
import 'token_holder.dart';
import 'token_balance.dart';
import 'token_balances_result.dart';
import 'token_transfer.dart';
import 'token_transfers_result.dart';
import 'token_transactions_result.dart';
import 'token_info_result.dart';
import 'token_holders_result.dart';
import 'send_transaction_result.dart';
import 'tokens_list_result.dart';
import 'wallet_info.dart';
import 'actual_fee_get_result.dart';
import 'wallets_get_result.dart';
import 'trusted_info.dart';
import 'trusted_get_result.dart';
import 'sync_state_result.dart';
import 'execute_count_get_result.dart';
import 'token_filters.dart';
import 'transactions_list.dart';
import 'transactions_list_flow_result.dart';
import 'multiple_request_ids.dart';
import 'addresses.dart';
import 'wallet_balance.dart';
import 'wallet_balance_full.dart';
import 'wallet_balance_results.dart';
import 'accepted_request_id.dart';
import 'round_data.dart';

class CumulativeAmount implements TBase {
  static final TStruct _STRUCT_DESC = TStruct("CumulativeAmount");
  static final TField _INTEGRAL_FIELD_DESC = TField("integral", TType.I64, 1);
  static final TField _FRACTION_FIELD_DESC = TField("fraction", TType.I64, 2);

  int _integral = 0;
  static const int INTEGRAL = 1;
  int _fraction = 0;
  static const int FRACTION = 2;


  CumulativeAmount() {
    this.integral = 0;

    this.fraction = 0;

  }

  // integral
  int get integral => this._integral;

  set integral(int integral) {
    this._integral = integral;
  }

  // fraction
  int get fraction => this._fraction;

  set fraction(int fraction) {
    this._fraction = fraction;
  }

  @override
  read(TProtocol iprot) {
    bool __isset_integral = false;
    bool __isset_fraction = false;
    TField field;
    iprot.readStructBegin();
    while (true) {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) {
        break;
      }
      switch (field.id) {
        case INTEGRAL:
          if (field.type == TType.I64) {
            this.integral = iprot.readI64();
            __isset_integral = true;
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case FRACTION:
          if (field.type == TType.I64) {
            this.fraction = iprot.readI64();
            __isset_fraction = true;
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    if (!__isset_integral) {
        throw TProtocolError(TProtocolErrorType.UNKNOWN, "Required field 'integral' was not found in serialized data! Struct: " + toString());
    }

    if (!__isset_fraction) {
        throw TProtocolError(TProtocolErrorType.UNKNOWN, "Required field 'fraction' was not found in serialized data! Struct: " + toString());
    }

    validate();
  }

  @override
  write(TProtocol oprot) {
    validate();

    oprot.writeStructBegin(_STRUCT_DESC);
    oprot.writeFieldBegin(_INTEGRAL_FIELD_DESC);
    oprot.writeI64(this.integral);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_FRACTION_FIELD_DESC);
    oprot.writeI64(this.fraction);
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @override
  String toString() {
    StringBuffer ret = StringBuffer("CumulativeAmount(");

    ret.write("integral:");
    ret.write(this.integral);

    ret.write(", ");
    ret.write("fraction:");
    ret.write(this.fraction);

    ret.write(")");

    return ret.toString();
  }

  validate() {
    // check for required fields
    // alas, we cannot check 'integral' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'fraction' because it's a primitive and you chose the non-beans generator.
    // check that fields of type enum have valid values
  }

}

