/// Autogenerated by Thrift Compiler (0.20.0)
/// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
///  @generated


// ignore_for_file: unused_import
library api.src.smart_operation_state;

class SmartOperationState {
  static const int SOS_Pending = 0;
  static const int SOS_Success = 1;
  static const int SOS_Failed = 2;

  static final VALID_VALUES = {
    SOS_Pending
    , SOS_Success
    , SOS_Failed
  };
  static final Map<int, String> VALUES_TO_NAMES = {
    SOS_Pending: 'SOS_Pending'
    , SOS_Success: 'SOS_Success'
    , SOS_Failed: 'SOS_Failed'
  };
}
