/// Autogenerated by Thrift Compiler (0.20.0)
/// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
///  @generated


// ignore_for_file: unused_import
library api.src.tokens_list_sort_field;

class TokensListSortField {
  static const int TL_Code = 0;
  static const int TL_Name = 1;
  static const int TL_Address = 2;
  static const int TL_TotalSupply = 3;
  static const int TL_HoldersCount = 4;
  static const int TL_TransfersCount = 5;
  static const int TL_TransactionsCount = 6;

  static final VALID_VALUES = {
    TL_Code
    , TL_Name
    , TL_Address
    , TL_TotalSupply
    , TL_HoldersCount
    , TL_TransfersCount
    , TL_TransactionsCount
  };
  static final Map<int, String> VALUES_TO_NAMES = {
    TL_Code: 'TL_Code'
    , TL_Name: 'TL_Name'
    , TL_Address: 'TL_Address'
    , TL_TotalSupply: 'TL_TotalSupply'
    , TL_HoldersCount: 'TL_HoldersCount'
    , TL_TransfersCount: 'TL_TransfersCount'
    , TL_TransactionsCount: 'TL_TransactionsCount'
  };
}
