/// Autogenerated by Thrift Compiler (0.20.0)
/// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
///  @generated


// ignore_for_file: unused_import
library api.src.selected_token_transfers;

//import 'package:thrift/src/protocol/t_protocol.dart';
import 'package:thrift/thrift.dart';
import 'transaction_type.dart';
import 'smart_operation_state.dart';
import 'transaction_state.dart';
import 'tokens_list_sort_field.dart';
import 'token_holders_sort_field.dart';
import 'wallets_list_sort.dart';
import 'package:general/general.dart' as t_general;
import 'amount_commission.dart';
import 'cumulative_amount.dart';
import 'smart_contract_deploy.dart';
import 'smart_contract.dart';
import 'smart_contract_invocation.dart';
import 'transaction_id.dart';
import 'token_deploy_trans_info.dart';
import 'token_transfer_trans_info.dart';
import 'smart_deploy_trans_info.dart';
import 'smart_execution_trans_info.dart';
import 'extra_fee.dart';
import 'smart_state_trans_info.dart';
import 'smart_trans_info.dart';
import 'transaction.dart';
import 'sealed_transaction.dart';
import 'short_transaction.dart';
import 'pool.dart';
import 'delegated_item.dart';
import 'delegated.dart';
import 'wallet_data.dart';
import 'period_stats.dart';
import 'wallet_data_get_result.dart';
import 'wallet_id_get_result.dart';
import 'wallet_transactions_count_get_result.dart';
import 'wallet_balance_get_result.dart';
import 'transaction_get_result.dart';
import 'transactions_get_result.dart';
import 'transaction_flow_result.dart';
import 'single_token_query.dart';
import 'single_query.dart';
import 'transactions_query.dart';
import 'selected_token_transfers.dart';
import 'public_key_transactions.dart';
import 'filtered_transactions_list_result.dart';
import 'pool_list_get_result.dart';
import 'pool_info_get_result.dart';
import 'pool_transactions_get_result.dart';
import 'stats_get_result.dart';
import 'smart_contract_get_result.dart';
import 'smart_contract_addresses_list_get_result.dart';
import 'smart_contracts_list_get_result.dart';
import 'transactions_state_get_result.dart';
import 'smart_method_params_get_result.dart';
import 'contract_all_methods_get_result.dart';
import 'smart_contract_method_argument.dart';
import 'smart_contract_method.dart';
import 'smart_contract_data_result.dart';
import 'smart_contract_compile_result.dart';
import 'token_info.dart';
import 'token_transaction.dart';
import 'token_holder.dart';
import 'token_balance.dart';
import 'token_balances_result.dart';
import 'token_transfer.dart';
import 'token_transfers_result.dart';
import 'token_transactions_result.dart';
import 'token_info_result.dart';
import 'token_holders_result.dart';
import 'send_transaction_result.dart';
import 'tokens_list_result.dart';
import 'wallet_info.dart';
import 'actual_fee_get_result.dart';
import 'wallets_get_result.dart';
import 'trusted_info.dart';
import 'trusted_get_result.dart';
import 'sync_state_result.dart';
import 'execute_count_get_result.dart';
import 'token_filters.dart';
import 'transactions_list.dart';
import 'transactions_list_flow_result.dart';
import 'multiple_request_ids.dart';
import 'addresses.dart';
import 'wallet_balance.dart';
import 'wallet_balance_full.dart';
import 'wallet_balance_results.dart';
import 'accepted_request_id.dart';
import 'round_data.dart';

class SelectedTokenTransfers implements TBase {
  static final TStruct _STRUCT_DESC = TStruct("SelectedTokenTransfers");
  static final TField _TOKEN_ADDRESS_FIELD_DESC = TField("tokenAddress", TType.STRING, 1);
  static final TField _TOKEN_NAME_FIELD_DESC = TField("tokenName", TType.STRING, 2);
  static final TField _TOKEN_TIKER_FIELD_DESC = TField("tokenTiker", TType.STRING, 3);
  static final TField _TRANSFERS_FIELD_DESC = TField("transfers", TType.LIST, 4);

  Uint8List _tokenAddress = "";
  static const int TOKENADDRESS = 1;
  String _tokenName = "";
  static const int TOKENNAME = 2;
  String _tokenTiker = "";
  static const int TOKENTIKER = 3;
  List<TokenTransfer> _transfers = [];
  static const int TRANSFERS = 4;


  SelectedTokenTransfers() {
  }

  // tokenAddress
  Uint8List get tokenAddress => this._tokenAddress;

  set tokenAddress(Uint8List tokenAddress) {
    this._tokenAddress = tokenAddress;
  }

  // tokenName
  String get tokenName => this._tokenName;

  set tokenName(String tokenName) {
    this._tokenName = tokenName;
  }

  // tokenTiker
  String get tokenTiker => this._tokenTiker;

  set tokenTiker(String tokenTiker) {
    this._tokenTiker = tokenTiker;
  }

  // transfers
  List<TokenTransfer> get transfers => this._transfers;

  set transfers(List<TokenTransfer> transfers) {
    this._transfers = transfers;
  }

  @override
  read(TProtocol iprot) {
    bool __isset_tokenAddress = false;
    bool __isset_tokenName = false;
    bool __isset_tokenTiker = false;
    bool __isset_transfers = false;
    TField field;
    iprot.readStructBegin();
    while (true) {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) {
        break;
      }
      switch (field.id) {
        case TOKENADDRESS:
          if (field.type == TType.STRING) {
            this.tokenAddress = iprot.readBinary();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case TOKENNAME:
          if (field.type == TType.STRING) {
            this.tokenName = iprot.readString();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case TOKENTIKER:
          if (field.type == TType.STRING) {
            this.tokenTiker = iprot.readString();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case TRANSFERS:
          if (field.type == TType.LIST) {
            {
              TList _list62 = iprot.readListBegin();
              this.transfers = [];
              for (int _i63 = 0; _i63 < _list62.length; ++_i63) {
                TokenTransfer _elem64;//declare element for this.transfers
                _elem64 = TokenTransfer();
                _elem64.read(iprot);
                this.transfers.add(_elem64);//add element to parent this.transfers
              }
              iprot.readListEnd();
            }
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  @override
  write(TProtocol oprot) {
    validate();

    oprot.writeStructBegin(_STRUCT_DESC);
    oprot.writeFieldBegin(_TOKEN_ADDRESS_FIELD_DESC);
    oprot.writeBinary(this.tokenAddress);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_TOKEN_NAME_FIELD_DESC);
    oprot.writeString(this.tokenName);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_TOKEN_TIKER_FIELD_DESC);
    oprot.writeString(this.tokenTiker);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_TRANSFERS_FIELD_DESC);
    {
      oprot.writeListBegin(TList(TType.STRUCT, this.transfers.length));
      for (var elem65 in this.transfers) {
        elem65.write(oprot);
      }
      oprot.writeListEnd();
    }
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @override
  String toString() {
    StringBuffer ret = StringBuffer("SelectedTokenTransfers(");

    ret.write("tokenAddress:");
    ret.write(this.tokenAddress);

    ret.write(", ");
    ret.write("tokenName:");
    ret.write(this.tokenName);

    ret.write(", ");
    ret.write("tokenTiker:");
    ret.write(this.tokenTiker);

    ret.write(", ");
    ret.write("transfers:");
    ret.write(this.transfers);

    ret.write(")");

    return ret.toString();
  }

  validate() {
    // check for required fields
    // check that fields of type enum have valid values
  }

}

