/// Autogenerated by Thrift Compiler (0.20.0)
/// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
///  @generated


// ignore_for_file: unused_import
library api.src.token_holders_sort_field;

class TokenHoldersSortField {
  static const int TH_Balance = 0;
  static const int TH_TransfersCount = 1;

  static final VALID_VALUES = {
    TH_Balance
    , TH_TransfersCount
  };
  static final Map<int, String> VALUES_TO_NAMES = {
    TH_Balance: 'TH_Balance'
    , TH_TransfersCount: 'TH_TransfersCount'
  };
}
