/// Autogenerated by Thrift Compiler (0.20.0)
/// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
///  @generated


// ignore_for_file: unused_import
library api.src.token_transaction;

//import 'package:thrift/src/protocol/t_protocol.dart';
import 'package:thrift/thrift.dart';
import 'transaction_type.dart';
import 'smart_operation_state.dart';
import 'transaction_state.dart';
import 'tokens_list_sort_field.dart';
import 'token_holders_sort_field.dart';
import 'wallets_list_sort.dart';
import 'package:general/general.dart' as t_general;
import 'amount_commission.dart';
import 'cumulative_amount.dart';
import 'smart_contract_deploy.dart';
import 'smart_contract.dart';
import 'smart_contract_invocation.dart';
import 'transaction_id.dart';
import 'token_deploy_trans_info.dart';
import 'token_transfer_trans_info.dart';
import 'smart_deploy_trans_info.dart';
import 'smart_execution_trans_info.dart';
import 'extra_fee.dart';
import 'smart_state_trans_info.dart';
import 'smart_trans_info.dart';
import 'transaction.dart';
import 'sealed_transaction.dart';
import 'short_transaction.dart';
import 'pool.dart';
import 'delegated_item.dart';
import 'delegated.dart';
import 'wallet_data.dart';
import 'period_stats.dart';
import 'wallet_data_get_result.dart';
import 'wallet_id_get_result.dart';
import 'wallet_transactions_count_get_result.dart';
import 'wallet_balance_get_result.dart';
import 'transaction_get_result.dart';
import 'transactions_get_result.dart';
import 'transaction_flow_result.dart';
import 'single_token_query.dart';
import 'single_query.dart';
import 'transactions_query.dart';
import 'selected_token_transfers.dart';
import 'public_key_transactions.dart';
import 'filtered_transactions_list_result.dart';
import 'pool_list_get_result.dart';
import 'pool_info_get_result.dart';
import 'pool_transactions_get_result.dart';
import 'stats_get_result.dart';
import 'smart_contract_get_result.dart';
import 'smart_contract_addresses_list_get_result.dart';
import 'smart_contracts_list_get_result.dart';
import 'transactions_state_get_result.dart';
import 'smart_method_params_get_result.dart';
import 'contract_all_methods_get_result.dart';
import 'smart_contract_method_argument.dart';
import 'smart_contract_method.dart';
import 'smart_contract_data_result.dart';
import 'smart_contract_compile_result.dart';
import 'token_info.dart';
import 'token_transaction.dart';
import 'token_holder.dart';
import 'token_balance.dart';
import 'token_balances_result.dart';
import 'token_transfer.dart';
import 'token_transfers_result.dart';
import 'token_transactions_result.dart';
import 'token_info_result.dart';
import 'token_holders_result.dart';
import 'send_transaction_result.dart';
import 'tokens_list_result.dart';
import 'wallet_info.dart';
import 'actual_fee_get_result.dart';
import 'wallets_get_result.dart';
import 'trusted_info.dart';
import 'trusted_get_result.dart';
import 'sync_state_result.dart';
import 'execute_count_get_result.dart';
import 'token_filters.dart';
import 'transactions_list.dart';
import 'transactions_list_flow_result.dart';
import 'multiple_request_ids.dart';
import 'addresses.dart';
import 'wallet_balance.dart';
import 'wallet_balance_full.dart';
import 'wallet_balance_results.dart';
import 'accepted_request_id.dart';
import 'round_data.dart';

class TokenTransaction implements TBase {
  static final TStruct _STRUCT_DESC = TStruct("TokenTransaction");
  static final TField _TOKEN_FIELD_DESC = TField("token", TType.STRING, 1);
  static final TField _TRANSACTION_FIELD_DESC = TField("transaction", TType.STRUCT, 2);
  static final TField _TIME_FIELD_DESC = TField("time", TType.I64, 3);
  static final TField _INITIATOR_FIELD_DESC = TField("initiator", TType.STRING, 4);
  static final TField _METHOD_FIELD_DESC = TField("method", TType.STRING, 5);
  static final TField _PARAMS_FIELD_DESC = TField("params", TType.LIST, 6);
  static final TField _STATE_FIELD_DESC = TField("state", TType.I32, 7);

  Uint8List _token = "";
  static const int TOKEN = 1;
  TransactionId _transaction = TransactionId();
  static const int TRANSACTION = 2;
  int _time = 0;
  static const int TIME = 3;
  Uint8List _initiator = "";
  static const int INITIATOR = 4;
  String _method = "";
  static const int METHOD = 5;
  List<t_general.Variant> _params = [];
  static const int PARAMS = 6;
  int _state = 0;
  static const int STATE = 7;


  TokenTransaction() {
  }

  // token
  Uint8List get token => this._token;

  set token(Uint8List token) {
    this._token = token;
  }

  // transaction
  TransactionId get transaction => this._transaction;

  set transaction(TransactionId transaction) {
    this._transaction = transaction;
  }

  // time
  int get time => this._time;

  set time(int time) {
    this._time = time;
  }

  // initiator
  Uint8List get initiator => this._initiator;

  set initiator(Uint8List initiator) {
    this._initiator = initiator;
  }

  // method
  String get method => this._method;

  set method(String method) {
    this._method = method;
  }

  // params
  List<t_general.Variant> get params => this._params;

  set params(List<t_general.Variant> params) {
    this._params = params;
  }

  // state
  int get state => this._state;

  set state(int state) {
    this._state = state;
  }

  @override
  read(TProtocol iprot) {
    bool __isset_token = false;
    bool __isset_transaction = false;
    bool __isset_time = false;
    bool __isset_initiator = false;
    bool __isset_method = false;
    bool __isset_params = false;
    bool __isset_state = false;
    TField field;
    iprot.readStructBegin();
    while (true) {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) {
        break;
      }
      switch (field.id) {
        case TOKEN:
          if (field.type == TType.STRING) {
            this.token = iprot.readBinary();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case TRANSACTION:
          if (field.type == TType.STRUCT) {
            this.transaction = TransactionId();
            this.transaction.read(iprot);
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case TIME:
          if (field.type == TType.I64) {
            this.time = iprot.readI64();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case INITIATOR:
          if (field.type == TType.STRING) {
            this.initiator = iprot.readBinary();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case METHOD:
          if (field.type == TType.STRING) {
            this.method = iprot.readString();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case PARAMS:
          if (field.type == TType.LIST) {
            {
              TList _list134 = iprot.readListBegin();
              this.params = [];
              for (int _i135 = 0; _i135 < _list134.length; ++_i135) {
                t_general.Variant _elem136;//declare element for this.params
                _elem136 = t_general.Variant();
                _elem136.read(iprot);
                this.params.add(_elem136);//add element to parent this.params
              }
              iprot.readListEnd();
            }
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case STATE:
          if (field.type == TType.I32) {
            this.state = iprot.readI32();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  @override
  write(TProtocol oprot) {
    validate();

    oprot.writeStructBegin(_STRUCT_DESC);
    oprot.writeFieldBegin(_TOKEN_FIELD_DESC);
    oprot.writeBinary(this.token);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_TRANSACTION_FIELD_DESC);
    this.transaction.write(oprot);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_TIME_FIELD_DESC);
    oprot.writeI64(this.time);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_INITIATOR_FIELD_DESC);
    oprot.writeBinary(this.initiator);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_METHOD_FIELD_DESC);
    oprot.writeString(this.method);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_PARAMS_FIELD_DESC);
    {
      oprot.writeListBegin(TList(TType.STRUCT, this.params.length));
      for (var elem137 in this.params) {
        elem137.write(oprot);
      }
      oprot.writeListEnd();
    }
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_STATE_FIELD_DESC);
    oprot.writeI32(this.state);
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @override
  String toString() {
    StringBuffer ret = StringBuffer("TokenTransaction(");

    ret.write("token:");
    ret.write(this.token);

    ret.write(", ");
    ret.write("transaction:");
    ret.write(this.transaction);

    ret.write(", ");
    ret.write("time:");
    ret.write(this.time);

    ret.write(", ");
    ret.write("initiator:");
    ret.write(this.initiator);

    ret.write(", ");
    ret.write("method:");
    ret.write(this.method);

    ret.write(", ");
    ret.write("params:");
    ret.write(this.params);

    ret.write(", ");
    ret.write("state:");
    String state_name = SmartOperationState.VALUES_TO_NAMES[this.state]!;
    if (state_name != null) {
      ret.write(state_name);
      ret.write(" (");
    }
    ret.write(this.state);
    if (state_name != null) {
      ret.write(")");
    }

    ret.write(")");

    return ret.toString();
  }

  validate() {
    // check for required fields
    // check that fields of type enum have valid values
    if (isSetState() && !SmartOperationState.VALID_VALUES.contains(state)) {
      throw TProtocolError(TProtocolErrorType.UNKNOWN, "The field 'state' has been assigned the invalid value $state");
    }
  }

}

