/// Autogenerated by Thrift Compiler (0.20.0)
/// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
///  @generated


// ignore_for_file: unused_import
library api.src.token_transfer_trans_info;

//import 'package:thrift/src/protocol/t_protocol.dart';
import 'package:thrift/thrift.dart';
import 'transaction_type.dart';
import 'smart_operation_state.dart';
import 'transaction_state.dart';
import 'tokens_list_sort_field.dart';
import 'token_holders_sort_field.dart';
import 'wallets_list_sort.dart';
import 'package:general/general.dart' as t_general;
import 'amount_commission.dart';
import 'cumulative_amount.dart';
import 'smart_contract_deploy.dart';
import 'smart_contract.dart';
import 'smart_contract_invocation.dart';
import 'transaction_id.dart';
import 'token_deploy_trans_info.dart';
import 'token_transfer_trans_info.dart';
import 'smart_deploy_trans_info.dart';
import 'smart_execution_trans_info.dart';
import 'extra_fee.dart';
import 'smart_state_trans_info.dart';
import 'smart_trans_info.dart';
import 'transaction.dart';
import 'sealed_transaction.dart';
import 'short_transaction.dart';
import 'pool.dart';
import 'delegated_item.dart';
import 'delegated.dart';
import 'wallet_data.dart';
import 'period_stats.dart';
import 'wallet_data_get_result.dart';
import 'wallet_id_get_result.dart';
import 'wallet_transactions_count_get_result.dart';
import 'wallet_balance_get_result.dart';
import 'transaction_get_result.dart';
import 'transactions_get_result.dart';
import 'transaction_flow_result.dart';
import 'single_token_query.dart';
import 'single_query.dart';
import 'transactions_query.dart';
import 'selected_token_transfers.dart';
import 'public_key_transactions.dart';
import 'filtered_transactions_list_result.dart';
import 'pool_list_get_result.dart';
import 'pool_info_get_result.dart';
import 'pool_transactions_get_result.dart';
import 'stats_get_result.dart';
import 'smart_contract_get_result.dart';
import 'smart_contract_addresses_list_get_result.dart';
import 'smart_contracts_list_get_result.dart';
import 'transactions_state_get_result.dart';
import 'smart_method_params_get_result.dart';
import 'contract_all_methods_get_result.dart';
import 'smart_contract_method_argument.dart';
import 'smart_contract_method.dart';
import 'smart_contract_data_result.dart';
import 'smart_contract_compile_result.dart';
import 'token_info.dart';
import 'token_transaction.dart';
import 'token_holder.dart';
import 'token_balance.dart';
import 'token_balances_result.dart';
import 'token_transfer.dart';
import 'token_transfers_result.dart';
import 'token_transactions_result.dart';
import 'token_info_result.dart';
import 'token_holders_result.dart';
import 'send_transaction_result.dart';
import 'tokens_list_result.dart';
import 'wallet_info.dart';
import 'actual_fee_get_result.dart';
import 'wallets_get_result.dart';
import 'trusted_info.dart';
import 'trusted_get_result.dart';
import 'sync_state_result.dart';
import 'execute_count_get_result.dart';
import 'token_filters.dart';
import 'transactions_list.dart';
import 'transactions_list_flow_result.dart';
import 'multiple_request_ids.dart';
import 'addresses.dart';
import 'wallet_balance.dart';
import 'wallet_balance_full.dart';
import 'wallet_balance_results.dart';
import 'accepted_request_id.dart';
import 'round_data.dart';

class TokenTransferTransInfo implements TBase {
  static final TStruct _STRUCT_DESC = TStruct("TokenTransferTransInfo");
  static final TField _CODE_FIELD_DESC = TField("code", TType.STRING, 1);
  static final TField _SENDER_FIELD_DESC = TField("sender", TType.STRING, 2);
  static final TField _RECEIVER_FIELD_DESC = TField("receiver", TType.STRING, 3);
  static final TField _AMOUNT_FIELD_DESC = TField("amount", TType.STRING, 4);
  static final TField _STATE_FIELD_DESC = TField("state", TType.I32, 5);
  static final TField _STATE_TRANSACTION_FIELD_DESC = TField("stateTransaction", TType.STRUCT, 6);
  static final TField _TRANSFER_SUCCESS_FIELD_DESC = TField("transferSuccess", TType.BOOL, 7);

  String _code = "";
  static const int CODE = 1;
  Uint8List _sender = "";
  static const int SENDER = 2;
  Uint8List _receiver = "";
  static const int RECEIVER = 3;
  String _amount = "";
  static const int AMOUNT = 4;
  int _state = 0;
  static const int STATE = 5;
  TransactionId? _stateTransaction;
  static const int STATETRANSACTION = 6;
  bool? _transferSuccess;
  static const int TRANSFERSUCCESS = 7;

  //bool __isset_stateTransaction = false;
  //bool __isset_transferSuccess = false;

  TokenTransferTransInfo() {
  }

  // code
  String get code => this._code;

  set code(String code) {
    this._code = code;
  }

  // sender
  Uint8List get sender => this._sender;

  set sender(Uint8List sender) {
    this._sender = sender;
  }

  // receiver
  Uint8List get receiver => this._receiver;

  set receiver(Uint8List receiver) {
    this._receiver = receiver;
  }

  // amount
  String get amount => this._amount;

  set amount(String amount) {
    this._amount = amount;
  }

  // state
  int get state => this._state;

  set state(int state) {
    this._state = state;
  }

  // stateTransaction
  TransactionId? get stateTransaction => this._stateTransaction;

  set stateTransaction(TransactionId? stateTransaction) {
    this._stateTransaction = stateTransaction;
    //this.__isset_stateTransaction = true;
  }

  bool isSetStateTransaction() => this.stateTransaction != null;

  unsetStateTransaction() {
    this.stateTransaction = null;
  }

  // transferSuccess
  bool? get transferSuccess => this._transferSuccess;

  set transferSuccess(bool? transferSuccess) {
    this._transferSuccess = transferSuccess;
    //this.__isset_transferSuccess = true;
  }

  bool isSetTransferSuccess() => this.transferSuccess != null;

  unsetTransferSuccess() {
    this.transferSuccess = null;
  }

  @override
  read(TProtocol iprot) {
    bool __isset_code = false;
    bool __isset_sender = false;
    bool __isset_receiver = false;
    bool __isset_amount = false;
    bool __isset_state = false;
    TField field;
    iprot.readStructBegin();
    while (true) {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) {
        break;
      }
      switch (field.id) {
        case CODE:
          if (field.type == TType.STRING) {
            this.code = iprot.readString();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case SENDER:
          if (field.type == TType.STRING) {
            this.sender = iprot.readBinary();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case RECEIVER:
          if (field.type == TType.STRING) {
            this.receiver = iprot.readBinary();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case AMOUNT:
          if (field.type == TType.STRING) {
            this.amount = iprot.readString();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case STATE:
          if (field.type == TType.I32) {
            this.state = iprot.readI32();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case STATETRANSACTION:
          if (field.type == TType.STRUCT) {
            this.stateTransaction = TransactionId();
            this.stateTransaction!.read(iprot);
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case TRANSFERSUCCESS:
          if (field.type == TType.BOOL) {
            this.transferSuccess = iprot.readBool();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  @override
  write(TProtocol oprot) {
    validate();

    oprot.writeStructBegin(_STRUCT_DESC);
    oprot.writeFieldBegin(_CODE_FIELD_DESC);
    oprot.writeString(this.code);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_SENDER_FIELD_DESC);
    oprot.writeBinary(this.sender);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_RECEIVER_FIELD_DESC);
    oprot.writeBinary(this.receiver);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_AMOUNT_FIELD_DESC);
    oprot.writeString(this.amount);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_STATE_FIELD_DESC);
    oprot.writeI32(this.state);
    oprot.writeFieldEnd();
    if (isSetStateTransaction()) {
      oprot.writeFieldBegin(_STATE_TRANSACTION_FIELD_DESC);
      this.stateTransaction?.write(oprot);
      oprot.writeFieldEnd();
    }
    if (isSetTransferSuccess()) {
      oprot.writeFieldBegin(_TRANSFER_SUCCESS_FIELD_DESC);
      oprot.writeBool(this.transferSuccess!);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @override
  String toString() {
    StringBuffer ret = StringBuffer("TokenTransferTransInfo(");

    ret.write("code:");
    ret.write(this.code);

    ret.write(", ");
    ret.write("sender:");
    ret.write(this.sender);

    ret.write(", ");
    ret.write("receiver:");
    ret.write(this.receiver);

    ret.write(", ");
    ret.write("amount:");
    ret.write(this.amount);

    ret.write(", ");
    ret.write("state:");
    String state_name = SmartOperationState.VALUES_TO_NAMES[this.state]!;
    if (state_name != null) {
      ret.write(state_name);
      ret.write(" (");
    }
    ret.write(this.state);
    if (state_name != null) {
      ret.write(")");
    }

    if (isSetStateTransaction()) {
      ret.write(", ");
      ret.write("stateTransaction:");
      if (this.stateTransaction == null) {
        ret.write("null");
      } else {
        ret.write(this.stateTransaction);
      }
    }

    if (isSetTransferSuccess()) {
      ret.write(", ");
      ret.write("transferSuccess:");
      if (this.transferSuccess == null) {
        ret.write("null");
      } else {
        ret.write(this.transferSuccess);
      }
    }

    ret.write(")");

    return ret.toString();
  }

  validate() {
    // check for required fields
    // check that fields of type enum have valid values
    if (isSetState() && !SmartOperationState.VALID_VALUES.contains(state)) {
      throw TProtocolError(TProtocolErrorType.UNKNOWN, "The field 'state' has been assigned the invalid value $state");
    }
  }

}

