/// Autogenerated by Thrift Compiler (0.20.0)
/// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
///  @generated


// ignore_for_file: unused_import
library api.src.token_transfer;

//import 'package:thrift/src/protocol/t_protocol.dart';
import 'package:thrift/thrift.dart';
import 'transaction_type.dart';
import 'smart_operation_state.dart';
import 'transaction_state.dart';
import 'tokens_list_sort_field.dart';
import 'token_holders_sort_field.dart';
import 'wallets_list_sort.dart';
import 'package:general/general.dart' as t_general;
import 'amount_commission.dart';
import 'cumulative_amount.dart';
import 'smart_contract_deploy.dart';
import 'smart_contract.dart';
import 'smart_contract_invocation.dart';
import 'transaction_id.dart';
import 'token_deploy_trans_info.dart';
import 'token_transfer_trans_info.dart';
import 'smart_deploy_trans_info.dart';
import 'smart_execution_trans_info.dart';
import 'extra_fee.dart';
import 'smart_state_trans_info.dart';
import 'smart_trans_info.dart';
import 'transaction.dart';
import 'sealed_transaction.dart';
import 'short_transaction.dart';
import 'pool.dart';
import 'delegated_item.dart';
import 'delegated.dart';
import 'wallet_data.dart';
import 'period_stats.dart';
import 'wallet_data_get_result.dart';
import 'wallet_id_get_result.dart';
import 'wallet_transactions_count_get_result.dart';
import 'wallet_balance_get_result.dart';
import 'transaction_get_result.dart';
import 'transactions_get_result.dart';
import 'transaction_flow_result.dart';
import 'single_token_query.dart';
import 'single_query.dart';
import 'transactions_query.dart';
import 'selected_token_transfers.dart';
import 'public_key_transactions.dart';
import 'filtered_transactions_list_result.dart';
import 'pool_list_get_result.dart';
import 'pool_info_get_result.dart';
import 'pool_transactions_get_result.dart';
import 'stats_get_result.dart';
import 'smart_contract_get_result.dart';
import 'smart_contract_addresses_list_get_result.dart';
import 'smart_contracts_list_get_result.dart';
import 'transactions_state_get_result.dart';
import 'smart_method_params_get_result.dart';
import 'contract_all_methods_get_result.dart';
import 'smart_contract_method_argument.dart';
import 'smart_contract_method.dart';
import 'smart_contract_data_result.dart';
import 'smart_contract_compile_result.dart';
import 'token_info.dart';
import 'token_transaction.dart';
import 'token_holder.dart';
import 'token_balance.dart';
import 'token_balances_result.dart';
import 'token_transfer.dart';
import 'token_transfers_result.dart';
import 'token_transactions_result.dart';
import 'token_info_result.dart';
import 'token_holders_result.dart';
import 'send_transaction_result.dart';
import 'tokens_list_result.dart';
import 'wallet_info.dart';
import 'actual_fee_get_result.dart';
import 'wallets_get_result.dart';
import 'trusted_info.dart';
import 'trusted_get_result.dart';
import 'sync_state_result.dart';
import 'execute_count_get_result.dart';
import 'token_filters.dart';
import 'transactions_list.dart';
import 'transactions_list_flow_result.dart';
import 'multiple_request_ids.dart';
import 'addresses.dart';
import 'wallet_balance.dart';
import 'wallet_balance_full.dart';
import 'wallet_balance_results.dart';
import 'accepted_request_id.dart';
import 'round_data.dart';

class TokenTransfer implements TBase {
  static final TStruct _STRUCT_DESC = TStruct("TokenTransfer");
  static final TField _TOKEN_FIELD_DESC = TField("token", TType.STRING, 1);
  static final TField _CODE_FIELD_DESC = TField("code", TType.STRING, 2);
  static final TField _SENDER_FIELD_DESC = TField("sender", TType.STRING, 3);
  static final TField _RECEIVER_FIELD_DESC = TField("receiver", TType.STRING, 4);
  static final TField _AMOUNT_FIELD_DESC = TField("amount", TType.STRING, 5);
  static final TField _INITIATOR_FIELD_DESC = TField("initiator", TType.STRING, 6);
  static final TField _TRANSACTION_FIELD_DESC = TField("transaction", TType.STRUCT, 7);
  static final TField _TIME_FIELD_DESC = TField("time", TType.I64, 8);
  static final TField _STATE_FIELD_DESC = TField("state", TType.I32, 9);
  static final TField _USER_FIELDS_FIELD_DESC = TField("userFields", TType.STRING, 10);
  static final TField _FEE_FIELD_DESC = TField("fee", TType.STRUCT, 11);
  static final TField _EXTRA_FEE_FIELD_DESC = TField("extraFee", TType.LIST, 14);

  Uint8List _token = "";
  static const int TOKEN = 1;
  String _code = "";
  static const int CODE = 2;
  Uint8List _sender = "";
  static const int SENDER = 3;
  Uint8List _receiver = "";
  static const int RECEIVER = 4;
  String _amount = "";
  static const int AMOUNT = 5;
  Uint8List _initiator = "";
  static const int INITIATOR = 6;
  TransactionId _transaction = TransactionId();
  static const int TRANSACTION = 7;
  int _time = 0;
  static const int TIME = 8;
  int _state = 0;
  static const int STATE = 9;
  Uint8List? _userFields;
  static const int USERFIELDS = 10;
  AmountCommission _fee = AmountCommission();
  static const int FEE = 11;
  List<ExtraFee> _extraFee = [];
  static const int EXTRAFEE = 14;

  //bool __isset_userFields = false;

  TokenTransfer() {
  }

  // token
  Uint8List get token => this._token;

  set token(Uint8List token) {
    this._token = token;
  }

  // code
  String get code => this._code;

  set code(String code) {
    this._code = code;
  }

  // sender
  Uint8List get sender => this._sender;

  set sender(Uint8List sender) {
    this._sender = sender;
  }

  // receiver
  Uint8List get receiver => this._receiver;

  set receiver(Uint8List receiver) {
    this._receiver = receiver;
  }

  // amount
  String get amount => this._amount;

  set amount(String amount) {
    this._amount = amount;
  }

  // initiator
  Uint8List get initiator => this._initiator;

  set initiator(Uint8List initiator) {
    this._initiator = initiator;
  }

  // transaction
  TransactionId get transaction => this._transaction;

  set transaction(TransactionId transaction) {
    this._transaction = transaction;
  }

  // time
  int get time => this._time;

  set time(int time) {
    this._time = time;
  }

  // state
  int get state => this._state;

  set state(int state) {
    this._state = state;
  }

  // userFields
  Uint8List? get userFields => this._userFields;

  set userFields(Uint8List? userFields) {
    this._userFields = userFields;
    //this.__isset_userFields = true;
  }

  bool isSetUserFields() => this.userFields != null;

  unsetUserFields() {
    this.userFields = null;
  }

  // fee
  AmountCommission get fee => this._fee;

  set fee(AmountCommission fee) {
    this._fee = fee;
  }

  // extraFee
  List<ExtraFee> get extraFee => this._extraFee;

  set extraFee(List<ExtraFee> extraFee) {
    this._extraFee = extraFee;
  }

  @override
  read(TProtocol iprot) {
    bool __isset_token = false;
    bool __isset_code = false;
    bool __isset_sender = false;
    bool __isset_receiver = false;
    bool __isset_amount = false;
    bool __isset_initiator = false;
    bool __isset_transaction = false;
    bool __isset_time = false;
    bool __isset_state = false;
    bool __isset_fee = false;
    bool __isset_extraFee = false;
    TField field;
    iprot.readStructBegin();
    while (true) {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) {
        break;
      }
      switch (field.id) {
        case TOKEN:
          if (field.type == TType.STRING) {
            this.token = iprot.readBinary();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case CODE:
          if (field.type == TType.STRING) {
            this.code = iprot.readString();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case SENDER:
          if (field.type == TType.STRING) {
            this.sender = iprot.readBinary();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case RECEIVER:
          if (field.type == TType.STRING) {
            this.receiver = iprot.readBinary();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case AMOUNT:
          if (field.type == TType.STRING) {
            this.amount = iprot.readString();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case INITIATOR:
          if (field.type == TType.STRING) {
            this.initiator = iprot.readBinary();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case TRANSACTION:
          if (field.type == TType.STRUCT) {
            this.transaction = TransactionId();
            this.transaction.read(iprot);
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case TIME:
          if (field.type == TType.I64) {
            this.time = iprot.readI64();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case STATE:
          if (field.type == TType.I32) {
            this.state = iprot.readI32();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case USERFIELDS:
          if (field.type == TType.STRING) {
            this.userFields = iprot.readBinary();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case FEE:
          if (field.type == TType.STRUCT) {
            this.fee = AmountCommission();
            this.fee.read(iprot);
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case EXTRAFEE:
          if (field.type == TType.LIST) {
            {
              TList _list142 = iprot.readListBegin();
              this.extraFee = [];
              for (int _i143 = 0; _i143 < _list142.length; ++_i143) {
                ExtraFee _elem144;//declare element for this.extraFee
                _elem144 = ExtraFee();
                _elem144.read(iprot);
                this.extraFee.add(_elem144);//add element to parent this.extraFee
              }
              iprot.readListEnd();
            }
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  @override
  write(TProtocol oprot) {
    validate();

    oprot.writeStructBegin(_STRUCT_DESC);
    oprot.writeFieldBegin(_TOKEN_FIELD_DESC);
    oprot.writeBinary(this.token);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_CODE_FIELD_DESC);
    oprot.writeString(this.code);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_SENDER_FIELD_DESC);
    oprot.writeBinary(this.sender);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_RECEIVER_FIELD_DESC);
    oprot.writeBinary(this.receiver);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_AMOUNT_FIELD_DESC);
    oprot.writeString(this.amount);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_INITIATOR_FIELD_DESC);
    oprot.writeBinary(this.initiator);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_TRANSACTION_FIELD_DESC);
    this.transaction.write(oprot);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_TIME_FIELD_DESC);
    oprot.writeI64(this.time);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_STATE_FIELD_DESC);
    oprot.writeI32(this.state);
    oprot.writeFieldEnd();
    if (isSetUserFields()) {
      oprot.writeFieldBegin(_USER_FIELDS_FIELD_DESC);
      oprot.writeBinary(this.userFields!);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(_FEE_FIELD_DESC);
    this.fee.write(oprot);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_EXTRA_FEE_FIELD_DESC);
    {
      oprot.writeListBegin(TList(TType.STRUCT, this.extraFee.length));
      for (var elem145 in this.extraFee) {
        elem145.write(oprot);
      }
      oprot.writeListEnd();
    }
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @override
  String toString() {
    StringBuffer ret = StringBuffer("TokenTransfer(");

    ret.write("token:");
    ret.write(this.token);

    ret.write(", ");
    ret.write("code:");
    ret.write(this.code);

    ret.write(", ");
    ret.write("sender:");
    ret.write(this.sender);

    ret.write(", ");
    ret.write("receiver:");
    ret.write(this.receiver);

    ret.write(", ");
    ret.write("amount:");
    ret.write(this.amount);

    ret.write(", ");
    ret.write("initiator:");
    ret.write(this.initiator);

    ret.write(", ");
    ret.write("transaction:");
    ret.write(this.transaction);

    ret.write(", ");
    ret.write("time:");
    ret.write(this.time);

    ret.write(", ");
    ret.write("state:");
    String state_name = SmartOperationState.VALUES_TO_NAMES[this.state]!;
    if (state_name != null) {
      ret.write(state_name);
      ret.write(" (");
    }
    ret.write(this.state);
    if (state_name != null) {
      ret.write(")");
    }

    if (isSetUserFields()) {
      ret.write(", ");
      ret.write("userFields:");
      if (this.userFields == null) {
        ret.write("null");
      } else {
        ret.write("BINARY");
      }
    }

    ret.write(", ");
    ret.write("fee:");
    ret.write(this.fee);

    ret.write(", ");
    ret.write("extraFee:");
    ret.write(this.extraFee);

    ret.write(")");

    return ret.toString();
  }

  validate() {
    // check for required fields
    // check that fields of type enum have valid values
    if (isSetState() && !SmartOperationState.VALID_VALUES.contains(state)) {
      throw TProtocolError(TProtocolErrorType.UNKNOWN, "The field 'state' has been assigned the invalid value $state");
    }
  }

}

