/// Autogenerated by Thrift Compiler (0.20.0)
/// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
///  @generated


// ignore_for_file: unused_import
library api.src.transaction;

//import 'package:thrift/src/protocol/t_protocol.dart';
import 'package:thrift/thrift.dart';
import 'transaction_type.dart';
import 'smart_operation_state.dart';
import 'transaction_state.dart';
import 'tokens_list_sort_field.dart';
import 'token_holders_sort_field.dart';
import 'wallets_list_sort.dart';
import 'package:general/general.dart' as t_general;
import 'amount_commission.dart';
import 'cumulative_amount.dart';
import 'smart_contract_deploy.dart';
import 'smart_contract.dart';
import 'smart_contract_invocation.dart';
import 'transaction_id.dart';
import 'token_deploy_trans_info.dart';
import 'token_transfer_trans_info.dart';
import 'smart_deploy_trans_info.dart';
import 'smart_execution_trans_info.dart';
import 'extra_fee.dart';
import 'smart_state_trans_info.dart';
import 'smart_trans_info.dart';
import 'transaction.dart';
import 'sealed_transaction.dart';
import 'short_transaction.dart';
import 'pool.dart';
import 'delegated_item.dart';
import 'delegated.dart';
import 'wallet_data.dart';
import 'period_stats.dart';
import 'wallet_data_get_result.dart';
import 'wallet_id_get_result.dart';
import 'wallet_transactions_count_get_result.dart';
import 'wallet_balance_get_result.dart';
import 'transaction_get_result.dart';
import 'transactions_get_result.dart';
import 'transaction_flow_result.dart';
import 'single_token_query.dart';
import 'single_query.dart';
import 'transactions_query.dart';
import 'selected_token_transfers.dart';
import 'public_key_transactions.dart';
import 'filtered_transactions_list_result.dart';
import 'pool_list_get_result.dart';
import 'pool_info_get_result.dart';
import 'pool_transactions_get_result.dart';
import 'stats_get_result.dart';
import 'smart_contract_get_result.dart';
import 'smart_contract_addresses_list_get_result.dart';
import 'smart_contracts_list_get_result.dart';
import 'transactions_state_get_result.dart';
import 'smart_method_params_get_result.dart';
import 'contract_all_methods_get_result.dart';
import 'smart_contract_method_argument.dart';
import 'smart_contract_method.dart';
import 'smart_contract_data_result.dart';
import 'smart_contract_compile_result.dart';
import 'token_info.dart';
import 'token_transaction.dart';
import 'token_holder.dart';
import 'token_balance.dart';
import 'token_balances_result.dart';
import 'token_transfer.dart';
import 'token_transfers_result.dart';
import 'token_transactions_result.dart';
import 'token_info_result.dart';
import 'token_holders_result.dart';
import 'send_transaction_result.dart';
import 'tokens_list_result.dart';
import 'wallet_info.dart';
import 'actual_fee_get_result.dart';
import 'wallets_get_result.dart';
import 'trusted_info.dart';
import 'trusted_get_result.dart';
import 'sync_state_result.dart';
import 'execute_count_get_result.dart';
import 'token_filters.dart';
import 'transactions_list.dart';
import 'transactions_list_flow_result.dart';
import 'multiple_request_ids.dart';
import 'addresses.dart';
import 'wallet_balance.dart';
import 'wallet_balance_full.dart';
import 'wallet_balance_results.dart';
import 'accepted_request_id.dart';
import 'round_data.dart';

class Transaction implements TBase {
  static final TStruct _STRUCT_DESC = TStruct("Transaction");
  static final TField _ID_FIELD_DESC = TField("id", TType.I64, 1);
  static final TField _SOURCE_FIELD_DESC = TField("source", TType.STRING, 2);
  static final TField _TARGET_FIELD_DESC = TField("target", TType.STRING, 3);
  static final TField _AMOUNT_FIELD_DESC = TField("amount", TType.STRUCT, 4);
  static final TField _BALANCE_FIELD_DESC = TField("balance", TType.STRUCT, 5);
  static final TField _CURRENCY_FIELD_DESC = TField("currency", TType.BYTE, 6);
  static final TField _SIGNATURE_FIELD_DESC = TField("signature", TType.STRING, 7);
  static final TField _SMART_CONTRACT_FIELD_DESC = TField("smartContract", TType.STRUCT, 8);
  static final TField _FEE_FIELD_DESC = TField("fee", TType.STRUCT, 9);
  static final TField _TIME_CREATION_FIELD_DESC = TField("timeCreation", TType.I64, 10);
  static final TField _USER_FIELDS_FIELD_DESC = TField("userFields", TType.STRING, 11);
  static final TField _TYPE_FIELD_DESC = TField("type", TType.I32, 12);
  static final TField _SMART_INFO_FIELD_DESC = TField("smartInfo", TType.STRUCT, 13);
  static final TField _EXTRA_FEE_FIELD_DESC = TField("extraFee", TType.LIST, 14);
  static final TField _POOL_NUMBER_FIELD_DESC = TField("poolNumber", TType.I64, 15);
  static final TField _USED_CONTRACTS_FIELD_DESC = TField("usedContracts", TType.LIST, 16);

  int _id = 0;
  static const int ID = 1;
  Uint8List _source = "";
  static const int SOURCE = 2;
  Uint8List _target = "";
  static const int TARGET = 3;
  t_general.Amount _amount = t_general.Amount();
  static const int AMOUNT = 4;
  t_general.Amount _balance = t_general.Amount();
  static const int BALANCE = 5;
  int _currency = 0;
  static const int CURRENCY = 6;
  Uint8List _signature = "";
  static const int SIGNATURE = 7;
  SmartContractInvocation? _smartContract;
  static const int SMARTCONTRACT = 8;
  AmountCommission _fee = AmountCommission();
  static const int FEE = 9;
  int _timeCreation = 0;
  static const int TIMECREATION = 10;
  Uint8List? _userFields;
  static const int USERFIELDS = 11;
  int _type = 0;
  static const int TYPE = 12;
  SmartTransInfo? _smartInfo;
  static const int SMARTINFO = 13;
  List<ExtraFee>? _extraFee;
  static const int EXTRAFEE = 14;
  int _poolNumber = 0;
  static const int POOLNUMBER = 15;
  List<Uint8List>? _usedContracts;
  static const int USEDCONTRACTS = 16;

  //bool __isset_smartContract = false;
  //bool __isset_userFields = false;
  //bool __isset_smartInfo = false;
  //bool __isset_extraFee = false;
  //bool __isset_usedContracts = false;

  Transaction() {
  }

  // id
  int get id => this._id;

  set id(int id) {
    this._id = id;
  }

  // source
  Uint8List get source => this._source;

  set source(Uint8List source) {
    this._source = source;
  }

  // target
  Uint8List get target => this._target;

  set target(Uint8List target) {
    this._target = target;
  }

  // amount
  t_general.Amount get amount => this._amount;

  set amount(t_general.Amount amount) {
    this._amount = amount;
  }

  // balance
  t_general.Amount get balance => this._balance;

  set balance(t_general.Amount balance) {
    this._balance = balance;
  }

  // currency
  int get currency => this._currency;

  set currency(int currency) {
    this._currency = currency;
  }

  // signature
  Uint8List get signature => this._signature;

  set signature(Uint8List signature) {
    this._signature = signature;
  }

  // smartContract
  SmartContractInvocation? get smartContract => this._smartContract;

  set smartContract(SmartContractInvocation? smartContract) {
    this._smartContract = smartContract;
    //this.__isset_smartContract = true;
  }

  bool isSetSmartContract() => this.smartContract != null;

  unsetSmartContract() {
    this.smartContract = null;
  }

  // fee
  AmountCommission get fee => this._fee;

  set fee(AmountCommission fee) {
    this._fee = fee;
  }

  // timeCreation
  int get timeCreation => this._timeCreation;

  set timeCreation(int timeCreation) {
    this._timeCreation = timeCreation;
  }

  // userFields
  Uint8List? get userFields => this._userFields;

  set userFields(Uint8List? userFields) {
    this._userFields = userFields;
    //this.__isset_userFields = true;
  }

  bool isSetUserFields() => this.userFields != null;

  unsetUserFields() {
    this.userFields = null;
  }

  // type
  int get type => this._type;

  set type(int type) {
    this._type = type;
  }

  // smartInfo
  SmartTransInfo? get smartInfo => this._smartInfo;

  set smartInfo(SmartTransInfo? smartInfo) {
    this._smartInfo = smartInfo;
    //this.__isset_smartInfo = true;
  }

  bool isSetSmartInfo() => this.smartInfo != null;

  unsetSmartInfo() {
    this.smartInfo = null;
  }

  // extraFee
  List<ExtraFee>? get extraFee => this._extraFee;

  set extraFee(List<ExtraFee>? extraFee) {
    this._extraFee = extraFee;
  }

  bool isSetExtraFee() => this.extraFee != null;

  unsetExtraFee() {
    this.extraFee = null;
  }

  // poolNumber
  int get poolNumber => this._poolNumber;

  set poolNumber(int poolNumber) {
    this._poolNumber = poolNumber;
  }

  // usedContracts
  List<Uint8List>? get usedContracts => this._usedContracts;

  set usedContracts(List<Uint8List>? usedContracts) {
    this._usedContracts = usedContracts;
  }

  bool isSetUsedContracts() => this.usedContracts != null;

  unsetUsedContracts() {
    this.usedContracts = null;
  }

  @override
  read(TProtocol iprot) {
    bool __isset_id = false;
    bool __isset_source = false;
    bool __isset_target = false;
    bool __isset_amount = false;
    bool __isset_balance = false;
    bool __isset_currency = false;
    bool __isset_signature = false;
    bool __isset_fee = false;
    bool __isset_timeCreation = false;
    bool __isset_type = false;
    bool __isset_poolNumber = false;
    TField field;
    iprot.readStructBegin();
    while (true) {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) {
        break;
      }
      switch (field.id) {
        case ID:
          if (field.type == TType.I64) {
            this.id = iprot.readI64();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case SOURCE:
          if (field.type == TType.STRING) {
            this.source = iprot.readBinary();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case TARGET:
          if (field.type == TType.STRING) {
            this.target = iprot.readBinary();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case AMOUNT:
          if (field.type == TType.STRUCT) {
            this.amount = t_general.Amount();
            this.amount.read(iprot);
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case BALANCE:
          if (field.type == TType.STRUCT) {
            this.balance = t_general.Amount();
            this.balance.read(iprot);
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case CURRENCY:
          if (field.type == TType.BYTE) {
            this.currency = iprot.readByte();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case SIGNATURE:
          if (field.type == TType.STRING) {
            this.signature = iprot.readBinary();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case SMARTCONTRACT:
          if (field.type == TType.STRUCT) {
            this.smartContract = SmartContractInvocation();
            this.smartContract!.read(iprot);
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case FEE:
          if (field.type == TType.STRUCT) {
            this.fee = AmountCommission();
            this.fee.read(iprot);
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case TIMECREATION:
          if (field.type == TType.I64) {
            this.timeCreation = iprot.readI64();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case USERFIELDS:
          if (field.type == TType.STRING) {
            this.userFields = iprot.readBinary();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case TYPE:
          if (field.type == TType.I32) {
            this.type = iprot.readI32();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case SMARTINFO:
          if (field.type == TType.STRUCT) {
            this.smartInfo = SmartTransInfo();
            this.smartInfo!.read(iprot);
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case EXTRAFEE:
          if (field.type == TType.LIST) {
            {
              TList _list20 = iprot.readListBegin();
              this.extraFee = [];
              for (int _i21 = 0; _i21 < _list20.length; ++_i21) {
                ExtraFee _elem22;//declare element for this.extraFee
                _elem22 = ExtraFee();
                _elem22.read(iprot);
                this.extraFee?.add(_elem22);//add element to parent this.extraFee
              }
              iprot.readListEnd();
            }
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case POOLNUMBER:
          if (field.type == TType.I64) {
            this.poolNumber = iprot.readI64();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case USEDCONTRACTS:
          if (field.type == TType.LIST) {
            {
              TList _list23 = iprot.readListBegin();
              this.usedContracts = [];
              for (int _i24 = 0; _i24 < _list23.length; ++_i24) {
                Uint8List _elem25;//declare element for this.usedContracts
                _elem25 = iprot.readBinary();
                this.usedContracts?.add(_elem25);//add element to parent this.usedContracts
              }
              iprot.readListEnd();
            }
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  @override
  write(TProtocol oprot) {
    validate();

    oprot.writeStructBegin(_STRUCT_DESC);
    oprot.writeFieldBegin(_ID_FIELD_DESC);
    oprot.writeI64(this.id);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_SOURCE_FIELD_DESC);
    oprot.writeBinary(this.source);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_TARGET_FIELD_DESC);
    oprot.writeBinary(this.target);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_AMOUNT_FIELD_DESC);
    this.amount.write(oprot);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_BALANCE_FIELD_DESC);
    this.balance.write(oprot);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_CURRENCY_FIELD_DESC);
    oprot.writeByte(this.currency);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_SIGNATURE_FIELD_DESC);
    oprot.writeBinary(this.signature);
    oprot.writeFieldEnd();
    if (isSetSmartContract()) {
      oprot.writeFieldBegin(_SMART_CONTRACT_FIELD_DESC);
      this.smartContract?.write(oprot);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(_FEE_FIELD_DESC);
    this.fee.write(oprot);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(_TIME_CREATION_FIELD_DESC);
    oprot.writeI64(this.timeCreation);
    oprot.writeFieldEnd();
    if (isSetUserFields()) {
      oprot.writeFieldBegin(_USER_FIELDS_FIELD_DESC);
      oprot.writeBinary(this.userFields!);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(_TYPE_FIELD_DESC);
    oprot.writeI32(this.type);
    oprot.writeFieldEnd();
    if (isSetSmartInfo()) {
      oprot.writeFieldBegin(_SMART_INFO_FIELD_DESC);
      this.smartInfo?.write(oprot);
      oprot.writeFieldEnd();
    }
    if (isSetExtraFee()) {
      oprot.writeFieldBegin(_EXTRA_FEE_FIELD_DESC);
      {
        oprot.writeListBegin(TList(TType.STRUCT, this.extraFee!.length));
        for (var elem26 in this.extraFee!) {
          elem26.write(oprot);
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(_POOL_NUMBER_FIELD_DESC);
    oprot.writeI64(this.poolNumber);
    oprot.writeFieldEnd();
    if (isSetUsedContracts()) {
      oprot.writeFieldBegin(_USED_CONTRACTS_FIELD_DESC);
      {
        oprot.writeListBegin(TList(TType.STRING, this.usedContracts!.length));
        for (var elem27 in this.usedContracts!) {
          oprot.writeBinary(elem27);
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @override
  String toString() {
    StringBuffer ret = StringBuffer("Transaction(");

    ret.write("id:");
    ret.write(this.id);

    ret.write(", ");
    ret.write("source:");
    ret.write(this.source);

    ret.write(", ");
    ret.write("target:");
    ret.write(this.target);

    ret.write(", ");
    ret.write("amount:");
    ret.write(this.amount);

    ret.write(", ");
    ret.write("balance:");
    ret.write(this.balance);

    ret.write(", ");
    ret.write("currency:");
    ret.write(this.currency);

    ret.write(", ");
    ret.write("signature:");
    ret.write("BINARY");

    if (isSetSmartContract()) {
      ret.write(", ");
      ret.write("smartContract:");
      if (this.smartContract == null) {
        ret.write("null");
      } else {
        ret.write(this.smartContract);
      }
    }

    ret.write(", ");
    ret.write("fee:");
    ret.write(this.fee);

    ret.write(", ");
    ret.write("timeCreation:");
    ret.write(this.timeCreation);

    if (isSetUserFields()) {
      ret.write(", ");
      ret.write("userFields:");
      if (this.userFields == null) {
        ret.write("null");
      } else {
        ret.write("BINARY");
      }
    }

    ret.write(", ");
    ret.write("type:");
    String type_name = TransactionType.VALUES_TO_NAMES[this.type]!;
    if (type_name != null) {
      ret.write(type_name);
      ret.write(" (");
    }
    ret.write(this.type);
    if (type_name != null) {
      ret.write(")");
    }

    if (isSetSmartInfo()) {
      ret.write(", ");
      ret.write("smartInfo:");
      if (this.smartInfo == null) {
        ret.write("null");
      } else {
        ret.write(this.smartInfo);
      }
    }

    if (isSetExtraFee()) {
      ret.write(", ");
      ret.write("extraFee:");
      if (this.extraFee == null) {
        ret.write("null");
      } else {
        ret.write(this.extraFee);
      }
    }

    ret.write(", ");
    ret.write("poolNumber:");
    ret.write(this.poolNumber);

    if (isSetUsedContracts()) {
      ret.write(", ");
      ret.write("usedContracts:");
      if (this.usedContracts == null) {
        ret.write("null");
      } else {
        ret.write(this.usedContracts);
      }
    }

    ret.write(")");

    return ret.toString();
  }

  validate() {
    // check for required fields
    // check that fields of type enum have valid values
    if (isSetType() && !TransactionType.VALID_VALUES.contains(type)) {
      throw TProtocolError(TProtocolErrorType.UNKNOWN, "The field 'type' has been assigned the invalid value $type");
    }
  }

}

