/// Autogenerated by Thrift Compiler (0.20.0)
/// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
///  @generated


// ignore_for_file: unused_import
library api.src.wallets_list_sort;

class WalletsListSort {
  static const int WL_CurrentSum = 0;
  static const int WL_CreationTime = 1;
  static const int WL_TransactionsCount = 2;

  static final VALID_VALUES = {
    WL_CurrentSum
    , WL_CreationTime
    , WL_TransactionsCount
  };
  static final Map<int, String> VALUES_TO_NAMES = {
    WL_CurrentSum: 'WL_CurrentSum'
    , WL_CreationTime: 'WL_CreationTime'
    , WL_TransactionsCount: 'WL_TransactionsCount'
  };
}
